---

- name: "Healthcheck | Wait for {{  sb_app_name }} to be healthy on URLs {{ sb_app_healthcheck_urls }}"
  uri:
    url: "{{ item }}"
    method: GET
    validate_certs: "{{ sb_app_healthcheck_urls_validate_certs | default('no') }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: "{{ sb_app_healthcheck_urls_retry_count }}"
  delay: "{{ sb_app_healthcheck_urls_retry_delay }}"
  with_items: "{{ sb_app_healthcheck_urls }}"
  when: >
    sb_app_healthcheck_urls is defined and
    sb_app_as_a_service

- name: "Healthcheck | Wait for {{  sb_app_name }} to be healthy on TCP Ports {{ sb_app_healthcheck_ports }}"
  wait_for:
    host: localhost
    port: "{{ item }}"
    timeout: "{{ sb_app_healthcheck_ports_timeout }}"
  with_items: "{{ sb_app_healthcheck_ports }}"
  when: >
    sb_app_healthcheck_ports is defined and
    sb_app_as_a_service
