---
# tasks file for role_spring_boot_app

- import_tasks: prerequisites.yml

- import_tasks: check_vars.yml

- name: Set application destination folder
  set_fact:
    sb_app_artifact_destination_folder: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/{{ sb_app_version }}"

- name: Set artifact destination file
  set_fact:
    sb_app_artifact_destination_file: "{{ sb_app_artifact_destination_folder }}/{{ sb_app_artifact_id }}-{{ sb_app_version }}.{{ sb_app_extension }}"

- name: " Service | Check if use systemd"
  set_fact: use_system_d={{ ansible_service_mgr == 'systemd' }}

- debug: var=ansible_distribution_version

- name: " Service | Check if use use_initd"
  set_fact: use_initd={{ ansible_service_mgr == 'sysvinit' }}

- import_tasks: install.yml
  when: >
        sb_app_state == 'present'

- import_tasks: uninstall.yml
  when: >
        sb_app_state == 'absent'

- meta: flush_handlers

- import_tasks: healthcheck.yml
  when: >
        ((sb_app_healthcheck_urls is defined and
        sb_app_healthcheck_urls|length > 0) or
        (sb_app_healthcheck_ports is defined and
        sb_app_healthcheck_ports|length > 0)) and
        sb_app_state == 'present'
