---

- name: "Uninstall | Check if initd service Exists"
  stat:
    path: "/etc/init.d/{{ sb_app_name | lower }}"
  register: initd_service_status

- name: "Uninstall | Check if systemd service Exists"
  stat:
    path: "{{ sysd_script }}"
  register: systemd_service_status

- name: "Uninstall | Stop {{ sb_app_name | lower }} service"
  service:
    name: "{{ sb_app_name | lower }}"
    enabled: no
    state: stopped
  when: >
        ((initd_service_status.stat.exists and use_initd) or
        (systemd_service_status.stat.exists and use_system_d)) and
        sb_app_as_a_service
  become: true

- name: "Uninstall | Remove systemd service file"
  file:
    path: "{{ sysd_script }}"
    state: absent
  when: >
        systemd_service_status.stat.exists and use_system_d and sb_app_as_a_service
  become: true

- name: "Uninstall | Remove initd service file"
  file:
    path: "/etc/init.d/{{ sb_app_name | lower }}"
    state: absent
  when: >
        initd_service_status.stat.exists and use_initd and sb_app_as_a_service
  become: true

- name: "Uninstall | Remove app artifact symlink"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/{{ sb_app_name | upper }}"
    state: absent

- name: "Uninstall | Remove application service conf symlink"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/{{ sb_app_name }}.conf"
    state: absent

- name: "Uninstall | Remove application configuration symlink"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/application.yml"
    state: absent

- name: "Uninstall | Remove application logback  symlink"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/logback-spring.xml"
    state: absent
  when: >
        sb_app_logback_file_template_path is defined

- name: "Uninstall | Remove SystemV run folder"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/run"
    state: absent
  when: >
        not use_system_d

- name: "Uninstall | Remove app version folder"
  file:
    path: "{{ sb_applications_root_folder }}/{{ sb_app_name | upper }}/{{ sb_app_version }}"
    state: absent
