---
galaxy_info:
  author: orachide
  description: Deploy Spring Boot application as a service (initd or Systemd)
  company: chidix.fr

  license: license BSD

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - springboot
    - systemd
    - systemv
    - java

dependencies:
  - role: singleplatform-eng.users
    users_create_per_user_group: false
    groups_to_create: "{{ sb_user_groups_definitions | default(omit) }}"
    users: "{{ sb_users_definition }}"
    when: sb_app_create_users
  - role: geerlingguy.java
    when: sb_app_install_java
    java_packages:
      - "{{ sb_java_package }}"
