- name: SpringBoot
  hosts: all
  user: ec2-user
  become: true
  roles:
    - role: orachide.springboot_service
      sb_app_create_users: false
      sb_app_as_a_service: true
      sb_app_name: "{{ lookup('env','APP_NAME') }}"
      sb_app_group_id: "{{ lookup('env','GROUP') }}"
      sb_app_artifact_id: "{{ sb_app_name }}"
      sb_java_package: "java-{{ lookup('env','JAVA_VERSION') }}.0-openjdk"
      sb_app_version: "{{ lookup('env','APP_VERSION') }}"
      sb_app_user: ec2-user
      sb_app_user_group: ec2-user
      sb_app_extension: jar
      sb_app_artifact_file: "{{ playbook_dir }}/../build/libs/{{ sb_app_artifact_id }}-{{ sb_app_version }}.{{ sb_app_extension }}"
      sb_applications_root_folder: "/opt/{{ sb_app_name }}"
      sb_app_java_opts_xms: "{{ lookup('env','XMS') }}" 	
      sb_app_java_opts_xmx: "{{ lookup('env','XMX') }}"
      sb_app_healthcheck_urls: 
        - "http://{{ PUBLIC_DNS }}:8080"
      sb_app_env:
        - name: environment
          value: "{{ lookup('env','ENVIRONMENT') }}"

